from sqlalchemy.orm import Session
# pyrefly: ignore [missing-import]
from app.db.models import Framework

# ---------------------------------------------------------------------------
# Complete framework catalog: 42 frameworks across 4 stages
# Each entry carries full recommendation metadata for the rule engine.
# ---------------------------------------------------------------------------

INITIAL_FRAMEWORKS = [
    # ======================================================================
    # MANAGE (8 frameworks)
    # ======================================================================
    {
        "slug": "iso-14001",
        "name": "ISO 14001",
        "short_name": "ISO 14001",
        "full_name": "ISO 14001 — Environmental Management Systems",
        "stage": "manage",
        "topic": "governance",
        "subtopic": "environmental_management",
        "description": "Certifiable management system for controlling environmental impacts.",
        "what_it_is": "An international standard describing how to build an environmental management system (EMS): policy, aspects and impacts register, legal register, objectives, operational control, internal audit and management review.",
        "who_needs_it": [
            "Manufacturing, construction and logistics organisations with site-level impacts",
            "Suppliers whose customers require certified environmental management",
            "Organisations with no formal environmental governance yet"
        ],
        "geography_applicability": ["global"],
        "region_applicability": ["global"],
        "industry_fit": ["manufacturing", "energy", "chemicals", "construction", "transport", "consumer-goods", "agriculture", "mining"],
        "org_size_fit": ["sme", "mid", "enterprise"],
        "mandatory_status": "voluntary",
        "certifiable": True,
        "output_type": "certification",
        "prerequisites": [
            "Documented environmental policy signed by leadership",
            "Register of environmental aspects and applicable legal requirements",
            "Internal audit capability or an external auditor"
        ],
        "data_requirements": ["Environmental aspects register", "Legal compliance register", "Operational control procedures"],
        "maturity_min": "none",
        "maturity_max": "advanced",
        "implementation_effort": "medium",
        "assurance_relevance": "high",
        "depends_on": [],
        "recommended_next": ["iso-50001", "iso-45001", "ghg-protocol-corporate"],
        "priority_weight": 1.3,
        "recommendation_rule_notes": "Foundational for any organisation without an EMS. Gate-keep for measure and report frameworks.",
        "why_recommended_template": "Recommended because your organization {reason} and an Environmental Management System provides the governance backbone that later measurement and reporting frameworks assume.",
        "active": True,
    },
    {
        "slug": "iso-50001",
        "name": "ISO 50001",
        "short_name": "ISO 50001",
        "full_name": "ISO 50001 — Energy Management Systems",
        "stage": "manage",
        "topic": "energy",
        "subtopic": "energy_management",
        "description": "Management system dedicated to continual improvement of energy performance.",
        "what_it_is": "A standard for establishing an energy management system: energy review, baselines, energy performance indicators (EnPIs), and action plans that drive measurable consumption reduction.",
        "who_needs_it": [
            "Energy-intensive operations (cement, steel, chemicals, data centres, cold chain)",
            "Organisations where energy is a top-three operating cost",
            "Sites subject to mandatory energy audit regimes"
        ],
        "geography_applicability": ["global"],
        "region_applicability": ["global"],
        "industry_fit": ["manufacturing", "energy", "chemicals", "construction", "technology"],
        "org_size_fit": ["mid", "enterprise"],
        "mandatory_status": "voluntary",
        "certifiable": True,
        "output_type": "certification",
        "prerequisites": [
            "At least 12 months of metered energy consumption data",
            "Named energy manager or cross-functional energy team"
        ],
        "data_requirements": ["Metered energy consumption data (12+ months)", "Energy cost data", "Equipment and process inventory"],
        "maturity_min": "basic",
        "maturity_max": "advanced",
        "implementation_effort": "medium",
        "assurance_relevance": "medium",
        "depends_on": [],
        "recommended_next": ["ghg-protocol-corporate", "re100"],
        "priority_weight": 1.1,
        "recommendation_rule_notes": "Boost when energy_use_level is high or very-high.",
        "why_recommended_template": "Recommended because your organization has {energy_level} energy use, making energy a material cost and emissions driver.",
        "active": True,
    },
    {
        "slug": "iso-45001",
        "name": "ISO 45001",
        "short_name": "ISO 45001",
        "full_name": "ISO 45001 — Occupational Health & Safety",
        "stage": "manage",
        "topic": "social",
        "subtopic": "occupational_health_safety",
        "description": "Health and safety management system, often paired with ISO 14001.",
        "what_it_is": "A management system standard for occupational health and safety risk, using the same high-level structure as ISO 14001 so the two integrate cleanly into one HSE system.",
        "who_needs_it": [
            "Operations with field, plant or contractor workforces",
            "Organisations already certified to ISO 14001 seeking an integrated HSE system"
        ],
        "geography_applicability": ["global"],
        "region_applicability": ["global"],
        "industry_fit": ["manufacturing", "construction", "mining", "energy", "transport", "chemicals"],
        "org_size_fit": ["sme", "mid", "enterprise"],
        "mandatory_status": "voluntary",
        "certifiable": True,
        "output_type": "certification",
        "prerequisites": ["Incident reporting process", "Hazard identification and risk assessment"],
        "data_requirements": ["Incident/accident records", "Risk assessment register"],
        "maturity_min": "none",
        "maturity_max": "advanced",
        "implementation_effort": "medium",
        "assurance_relevance": "medium",
        "depends_on": [],
        "recommended_next": ["iso-14001", "sa8000"],
        "priority_weight": 0.9,
        "recommendation_rule_notes": "Boost for heavy industry with field/plant workforce.",
        "why_recommended_template": "Recommended because your {industry} operations carry occupational risk and ISO 45001 integrates with your environmental management system.",
        "active": True,
    },
    {
        "slug": "iso-37001",
        "name": "ISO 37001",
        "short_name": "ISO 37001",
        "full_name": "ISO 37001 — Anti-Bribery Management Systems",
        "stage": "manage",
        "topic": "governance",
        "subtopic": "anti_bribery",
        "description": "Management system for preventing, detecting and addressing bribery.",
        "what_it_is": "A certifiable standard for anti-bribery management: risk assessment, due diligence, financial and non-financial controls, reporting and investigation procedures.",
        "who_needs_it": [
            "Organisations operating in high-corruption-risk geographies",
            "Companies with public sector contracts or export exposure"
        ],
        "geography_applicability": ["global"],
        "region_applicability": ["global"],
        "industry_fit": ["construction", "energy", "mining", "finance", "healthcare"],
        "org_size_fit": ["mid", "enterprise"],
        "mandatory_status": "voluntary",
        "certifiable": True,
        "output_type": "certification",
        "prerequisites": ["Anti-bribery policy", "Risk assessment process"],
        "data_requirements": ["Third-party due diligence records", "Gift and hospitality registers"],
        "maturity_min": "basic",
        "maturity_max": "advanced",
        "implementation_effort": "medium",
        "assurance_relevance": "medium",
        "depends_on": [],
        "recommended_next": [],
        "priority_weight": 0.7,
        "recommendation_rule_notes": "Niche — boost only for governance-focused goals or high-corruption-risk regions.",
        "why_recommended_template": "Recommended because your organization operates in contexts where anti-bribery governance strengthens compliance and stakeholder trust.",
        "active": True,
    },
    {
        "slug": "iso-20400",
        "name": "ISO 20400",
        "short_name": "ISO 20400",
        "full_name": "ISO 20400 — Sustainable Procurement",
        "stage": "manage",
        "topic": "supply_chain",
        "subtopic": "sustainable_procurement",
        "description": "Guidance on integrating sustainability into procurement processes.",
        "what_it_is": "A guidance standard for embedding environmental and social criteria into procurement policy, supplier assessment, and contract management.",
        "who_needs_it": [
            "Organisations with complex supply chains and Scope 3 exposure",
            "Public sector buyers with sustainable procurement mandates"
        ],
        "geography_applicability": ["global"],
        "region_applicability": ["global"],
        "industry_fit": ["manufacturing", "construction", "consumer-goods", "technology", "retail"],
        "org_size_fit": ["mid", "enterprise"],
        "mandatory_status": "voluntary",
        "certifiable": False,
        "output_type": "standard",
        "prerequisites": ["Procurement policy", "Supplier assessment criteria"],
        "data_requirements": ["Supplier spend data", "Supplier environmental and social performance data"],
        "maturity_min": "basic",
        "maturity_max": "advanced",
        "implementation_effort": "medium",
        "assurance_relevance": "low",
        "depends_on": [],
        "recommended_next": ["ghg-protocol-scope3", "sa8000", "ecovadis"],
        "priority_weight": 0.8,
        "recommendation_rule_notes": "Boost when supply_chain_complexity is high.",
        "why_recommended_template": "Recommended because your supply chain complexity is {complexity}, making sustainable procurement governance important for managing value-chain risks.",
        "active": True,
    },
    {
        "slug": "iso-46001",
        "name": "ISO 46001",
        "short_name": "ISO 46001",
        "full_name": "ISO 46001 — Water Efficiency Management Systems",
        "stage": "manage",
        "topic": "water",
        "subtopic": "water_management",
        "description": "Management system for improving water efficiency and conservation.",
        "what_it_is": "A standard for establishing water efficiency management: water audit, baselines, water performance indicators, and conservation action plans.",
        "who_needs_it": [
            "Water-intensive operations (food & beverage, textiles, chemicals, agriculture)",
            "Facilities in water-stressed regions"
        ],
        "geography_applicability": ["global"],
        "region_applicability": ["global"],
        "industry_fit": ["manufacturing", "agriculture", "chemicals", "consumer-goods", "mining"],
        "org_size_fit": ["sme", "mid", "enterprise"],
        "mandatory_status": "voluntary",
        "certifiable": True,
        "output_type": "certification",
        "prerequisites": ["Water consumption metering data", "Water source and discharge mapping"],
        "data_requirements": ["Monthly water consumption data", "Water source quality data"],
        "maturity_min": "basic",
        "maturity_max": "advanced",
        "implementation_effort": "medium",
        "assurance_relevance": "medium",
        "depends_on": [],
        "recommended_next": ["iso-14046", "water-footprint", "cdp-water"],
        "priority_weight": 0.8,
        "recommendation_rule_notes": "Boost when water_intensity is high.",
        "why_recommended_template": "Recommended because your organization has high water intensity and a water efficiency management system reduces consumption and risk.",
        "active": True,
    },
    {
        "slug": "sa8000",
        "name": "SA8000",
        "short_name": "SA8000",
        "full_name": "SA8000 — Social Accountability",
        "stage": "manage",
        "topic": "social",
        "subtopic": "labour_rights",
        "description": "Certifiable social accountability standard covering labour rights and working conditions.",
        "what_it_is": "An auditable standard based on ILO conventions covering child labour, forced labour, health and safety, freedom of association, discrimination, working hours, remuneration, and management systems.",
        "who_needs_it": [
            "Suppliers in global value chains facing social audit requirements",
            "Organisations with large low-wage or contractor workforces"
        ],
        "geography_applicability": ["global"],
        "region_applicability": ["global"],
        "industry_fit": ["manufacturing", "consumer-goods", "agriculture", "construction", "retail"],
        "org_size_fit": ["sme", "mid", "enterprise"],
        "mandatory_status": "voluntary",
        "certifiable": True,
        "output_type": "certification",
        "prerequisites": ["Labour policy aligned with ILO core conventions", "Worker grievance mechanism"],
        "data_requirements": ["Working hours records", "Wage records", "Health and safety incident data"],
        "maturity_min": "none",
        "maturity_max": "advanced",
        "implementation_effort": "high",
        "assurance_relevance": "high",
        "depends_on": [],
        "recommended_next": ["iso-45001", "ungc-cop"],
        "priority_weight": 0.8,
        "recommendation_rule_notes": "Boost when supply_chain_complexity is high or customer_pressure is high.",
        "why_recommended_template": "Recommended because your supply chain footprint requires demonstrable social accountability to meet value-chain audit expectations.",
        "active": True,
    },
    {
        "slug": "aws-standard",
        "name": "AWS Standard",
        "short_name": "AWS",
        "full_name": "Alliance for Water Stewardship Standard",
        "stage": "manage",
        "topic": "water",
        "subtopic": "water_stewardship",
        "description": "Site-level water stewardship standard addressing shared water challenges.",
        "what_it_is": "A framework for responsible water use at the site and catchment level, covering water governance, balance, quality, water-related areas, and WASH access.",
        "who_needs_it": [
            "Facilities in water-stressed catchments",
            "Companies with CDP Water or investor water-risk obligations"
        ],
        "geography_applicability": ["global"],
        "region_applicability": ["global"],
        "industry_fit": ["manufacturing", "agriculture", "mining", "consumer-goods", "chemicals"],
        "org_size_fit": ["mid", "enterprise"],
        "mandatory_status": "voluntary",
        "certifiable": True,
        "output_type": "certification",
        "prerequisites": ["Site-level water balance data", "Catchment context assessment"],
        "data_requirements": ["Water intake, use, and discharge volumes", "Catchment risk assessment"],
        "maturity_min": "basic",
        "maturity_max": "advanced",
        "implementation_effort": "high",
        "assurance_relevance": "high",
        "depends_on": [],
        "recommended_next": ["cdp-water", "water-footprint"],
        "priority_weight": 0.7,
        "recommendation_rule_notes": "Boost when water_intensity is high.",
        "why_recommended_template": "Recommended because your high water intensity and site context call for a catchment-level stewardship approach.",
        "active": True,
    },

    # ======================================================================
    # MEASURE (11 frameworks)
    # ======================================================================
    {
        "slug": "ghg-protocol-corporate",
        "name": "GHG Protocol Corporate Standard",
        "short_name": "GHG Protocol",
        "full_name": "Greenhouse Gas Protocol — Corporate Standard",
        "stage": "measure",
        "topic": "climate",
        "subtopic": "emissions_accounting",
        "description": "The default accounting rulebook for Scope 1, 2 and 3 corporate emissions.",
        "what_it_is": "The globally accepted methodology for corporate greenhouse gas inventories. Defines organisational boundaries, Scope 1 (direct), Scope 2 (purchased energy) emissions.",
        "who_needs_it": [
            "Any organisation starting an emissions inventory",
            "Anyone preparing for CSRD, ISSB, BRSR, CDP or SBTi — all build on it"
        ],
        "geography_applicability": ["global"],
        "region_applicability": ["global"],
        "industry_fit": ["manufacturing", "energy", "chemicals", "construction", "transport", "technology", "consumer-goods", "agriculture", "finance", "healthcare", "mining", "retail"],
        "org_size_fit": ["startup", "sme", "mid", "enterprise"],
        "mandatory_status": "quasi_mandatory",
        "certifiable": False,
        "output_type": "methodology",
        "prerequisites": [
            "Activity data: fuel, electricity, travel, purchased goods",
            "Defined organisational and operational boundaries",
            "Emission factor source (national grid factors, DEFRA, IEA)"
        ],
        "data_requirements": ["Fuel consumption records", "Electricity bills", "Travel and logistics data", "Emission factors"],
        "maturity_min": "none",
        "maturity_max": "advanced",
        "implementation_effort": "medium",
        "assurance_relevance": "high",
        "depends_on": [],
        "recommended_next": ["ghg-protocol-scope2", "ghg-protocol-scope3", "iso-14064-1", "sbti"],
        "priority_weight": 1.5,
        "recommendation_rule_notes": "Highest priority measure framework. Prerequisite for nearly all reporting and target frameworks.",
        "why_recommended_template": "Recommended because {reason}. The GHG Protocol is the starting point — every reporting and target framework depends on this inventory.",
        "active": True,
    },
    {
        "slug": "ghg-protocol-scope2",
        "name": "GHG Protocol Scope 2 Guidance",
        "short_name": "Scope 2 Guidance",
        "full_name": "GHG Protocol — Scope 2 Guidance",
        "stage": "measure",
        "topic": "climate",
        "subtopic": "scope2_accounting",
        "description": "Detailed guidance for location-based and market-based Scope 2 accounting.",
        "what_it_is": "Guidance on accounting for emissions from purchased electricity, steam, heating and cooling using both location-based and market-based methods.",
        "who_needs_it": [
            "Organisations with significant purchased electricity",
            "Companies pursuing renewable energy sourcing or PPAs"
        ],
        "geography_applicability": ["global"],
        "region_applicability": ["global"],
        "industry_fit": ["manufacturing", "energy", "technology", "consumer-goods", "retail"],
        "org_size_fit": ["sme", "mid", "enterprise"],
        "mandatory_status": "voluntary",
        "certifiable": False,
        "output_type": "methodology",
        "prerequisites": ["GHG Protocol Corporate Standard inventory"],
        "data_requirements": ["Electricity consumption by source", "Grid emission factors", "Renewable energy certificates"],
        "maturity_min": "basic",
        "maturity_max": "advanced",
        "implementation_effort": "low",
        "assurance_relevance": "medium",
        "depends_on": ["ghg-protocol-corporate"],
        "recommended_next": ["re100", "ghg-protocol-scope3"],
        "priority_weight": 0.9,
        "recommendation_rule_notes": "Boost when energy_use_level is high and organisation has started Scope 2 accounting.",
        "why_recommended_template": "Recommended because your energy consumption is significant and dual-reporting (location and market-based) Scope 2 unlocks renewable energy procurement strategies.",
        "active": True,
    },
    {
        "slug": "ghg-protocol-scope3",
        "name": "GHG Protocol Scope 3 Standard",
        "short_name": "Scope 3 Standard",
        "full_name": "GHG Protocol — Corporate Value Chain (Scope 3) Standard",
        "stage": "measure",
        "topic": "climate",
        "subtopic": "scope3_accounting",
        "description": "Methodology for quantifying value-chain Scope 3 emissions across 15 categories.",
        "what_it_is": "Extends the Corporate Standard to cover the 15 categories of Scope 3 emissions: purchased goods, capital goods, fuel-and-energy, upstream transport, waste, business travel, employee commuting, upstream leased assets, downstream transport, processing, use of sold products, end-of-life, downstream leased assets, franchises, and investments.",
        "who_needs_it": [
            "Companies with material value-chain emissions",
            "Organisations preparing for SBTi (Scope 3 coverage required)"
        ],
        "geography_applicability": ["global"],
        "region_applicability": ["global"],
        "industry_fit": ["manufacturing", "consumer-goods", "retail", "construction", "finance", "technology"],
        "org_size_fit": ["mid", "enterprise"],
        "mandatory_status": "voluntary",
        "certifiable": False,
        "output_type": "methodology",
        "prerequisites": ["GHG Protocol Corporate Standard inventory", "Scope 3 screening or materiality assessment"],
        "data_requirements": ["Supplier spend or activity data", "Upstream and downstream logistics data", "Product life-cycle data"],
        "maturity_min": "basic",
        "maturity_max": "advanced",
        "implementation_effort": "high",
        "assurance_relevance": "high",
        "depends_on": ["ghg-protocol-corporate"],
        "recommended_next": ["sbti", "cdp-climate"],
        "priority_weight": 1.2,
        "recommendation_rule_notes": "Boost when supply_chain_complexity is high or customer_pressure is high.",
        "why_recommended_template": "Recommended because your supply chain footprint is likely material, making Scope 3 accounting relevant for target-setting and disclosure.",
        "active": True,
    },
    {
        "slug": "iso-14064-1",
        "name": "ISO 14064-1",
        "short_name": "ISO 14064-1",
        "full_name": "ISO 14064-1 — Organisation-Level GHG Quantification",
        "stage": "measure",
        "topic": "climate",
        "subtopic": "ghg_verification",
        "description": "Standard for quantifying and independently verifying organisation-level GHG inventories.",
        "what_it_is": "Part 1 of a three-part standard covering organisation-level GHG inventories, providing requirements for verification-ready quantification.",
        "who_needs_it": [
            "Organisations needing third-party assurance on emissions numbers",
            "Companies whose disclosures face limited or reasonable assurance requirements"
        ],
        "geography_applicability": ["global"],
        "region_applicability": ["global"],
        "industry_fit": ["manufacturing", "energy", "chemicals", "construction", "transport", "technology", "finance"],
        "org_size_fit": ["mid", "enterprise"],
        "mandatory_status": "voluntary",
        "certifiable": False,
        "output_type": "standard",
        "prerequisites": ["An existing GHG inventory, typically built to the GHG Protocol"],
        "data_requirements": ["Complete GHG inventory data", "Documented calculation methodology"],
        "maturity_min": "basic",
        "maturity_max": "advanced",
        "implementation_effort": "medium",
        "assurance_relevance": "high",
        "depends_on": ["ghg-protocol-corporate"],
        "recommended_next": ["iso-14064-2", "csrd", "brsr"],
        "priority_weight": 1.0,
        "recommendation_rule_notes": "Boost when emissions_maturity is basic/intermediate and assurance is needed.",
        "why_recommended_template": "Recommended because third-party verification of your emissions data protects your numbers under regulatory scrutiny and assurance requirements.",
        "active": True,
    },
    {
        "slug": "iso-14064-2",
        "name": "ISO 14064-2",
        "short_name": "ISO 14064-2",
        "full_name": "ISO 14064-2 — Project-Level GHG Reductions",
        "stage": "measure",
        "topic": "climate",
        "subtopic": "project_ghg",
        "description": "Standard for quantifying, monitoring and reporting GHG emission reductions from projects.",
        "what_it_is": "Part 2 of ISO 14064 covering project-level GHG reduction quantification: additionality, baselines, monitoring, and reporting for emission reduction projects.",
        "who_needs_it": [
            "Organisations implementing emission reduction projects",
            "Companies generating carbon credits or offsets"
        ],
        "geography_applicability": ["global"],
        "region_applicability": ["global"],
        "industry_fit": ["energy", "manufacturing", "construction", "agriculture"],
        "org_size_fit": ["mid", "enterprise"],
        "mandatory_status": "voluntary",
        "certifiable": False,
        "output_type": "standard",
        "prerequisites": ["Defined emission reduction project with baseline"],
        "data_requirements": ["Project baseline data", "Monitoring data for reductions"],
        "maturity_min": "intermediate",
        "maturity_max": "advanced",
        "implementation_effort": "medium",
        "assurance_relevance": "high",
        "depends_on": ["iso-14064-1"],
        "recommended_next": ["sbti", "net-zero-standard"],
        "priority_weight": 0.7,
        "recommendation_rule_notes": "Specialist — only boost when organisation has active reduction projects.",
        "why_recommended_template": "Recommended because your emission reduction projects need standardised quantification for credibility and potential credit generation.",
        "active": True,
    },
    {
        "slug": "iso-14067",
        "name": "ISO 14067",
        "short_name": "ISO 14067",
        "full_name": "ISO 14067 — Carbon Footprint of Products",
        "stage": "measure",
        "topic": "climate",
        "subtopic": "product_carbon_footprint",
        "description": "Standard for quantifying and communicating the carbon footprint of products.",
        "what_it_is": "Applies LCA principles specifically to greenhouse gas emissions of products, based on ISO 14040/14044, providing rules for product carbon footprint studies and communication.",
        "who_needs_it": [
            "Product manufacturers facing customer carbon footprint requests",
            "Companies making product-level climate claims"
        ],
        "geography_applicability": ["global"],
        "region_applicability": ["global"],
        "industry_fit": ["manufacturing", "consumer-goods", "agriculture", "construction"],
        "org_size_fit": ["sme", "mid", "enterprise"],
        "mandatory_status": "voluntary",
        "certifiable": False,
        "output_type": "methodology",
        "prerequisites": ["Bill of materials and process data", "LCA capability or consultancy access"],
        "data_requirements": ["Product life-cycle inventory data", "Energy and material inputs per unit"],
        "maturity_min": "intermediate",
        "maturity_max": "advanced",
        "implementation_effort": "high",
        "assurance_relevance": "medium",
        "depends_on": ["ghg-protocol-corporate"],
        "recommended_next": ["iso-14040", "iso-14044"],
        "priority_weight": 0.7,
        "recommendation_rule_notes": "Boost for product-manufacturing companies with customer PCF requirements.",
        "why_recommended_template": "Recommended because your product manufacturing operations face carbon footprint reporting requests from customers or regulations.",
        "active": True,
    },
    {
        "slug": "iso-14040",
        "name": "ISO 14040",
        "short_name": "ISO 14040",
        "full_name": "ISO 14040 — Life Cycle Assessment Principles",
        "stage": "measure",
        "topic": "climate",
        "subtopic": "life_cycle_assessment",
        "description": "Principles and framework for life cycle assessment (LCA).",
        "what_it_is": "A methodology framework for assessing environmental impacts of a product or service from raw material extraction through end of life.",
        "who_needs_it": [
            "Product manufacturers facing customer or retailer footprint requests",
            "Companies making product-level environmental claims"
        ],
        "geography_applicability": ["global"],
        "region_applicability": ["global"],
        "industry_fit": ["manufacturing", "consumer-goods", "construction", "agriculture"],
        "org_size_fit": ["mid", "enterprise"],
        "mandatory_status": "voluntary",
        "certifiable": False,
        "output_type": "methodology",
        "prerequisites": ["Bill of materials and process data", "Defined functional unit and boundaries"],
        "data_requirements": ["Life-cycle inventory data", "Impact assessment data"],
        "maturity_min": "intermediate",
        "maturity_max": "advanced",
        "implementation_effort": "high",
        "assurance_relevance": "medium",
        "depends_on": [],
        "recommended_next": ["iso-14044", "iso-14067"],
        "priority_weight": 0.7,
        "recommendation_rule_notes": "Specialist product-level framework.",
        "why_recommended_template": "Recommended because product-level environmental footprinting requires LCA methodology as the accepted standard.",
        "active": True,
    },
    {
        "slug": "iso-14044",
        "name": "ISO 14044",
        "short_name": "ISO 14044",
        "full_name": "ISO 14044 — Life Cycle Assessment Requirements",
        "stage": "measure",
        "topic": "climate",
        "subtopic": "life_cycle_assessment",
        "description": "Requirements and guidelines for life cycle assessment studies.",
        "what_it_is": "Specifies detailed requirements for conducting LCA studies including goal and scope definition, inventory analysis, impact assessment, and interpretation.",
        "who_needs_it": [
            "Organisations conducting formal LCA studies for EPDs or product claims",
            "Consultancies and internal teams performing LCA"
        ],
        "geography_applicability": ["global"],
        "region_applicability": ["global"],
        "industry_fit": ["manufacturing", "consumer-goods", "construction"],
        "org_size_fit": ["mid", "enterprise"],
        "mandatory_status": "voluntary",
        "certifiable": False,
        "output_type": "methodology",
        "prerequisites": ["ISO 14040 principles understanding", "LCA software or consultancy"],
        "data_requirements": ["Detailed process-level material and energy data"],
        "maturity_min": "intermediate",
        "maturity_max": "advanced",
        "implementation_effort": "high",
        "assurance_relevance": "medium",
        "depends_on": ["iso-14040"],
        "recommended_next": ["iso-14067"],
        "priority_weight": 0.6,
        "recommendation_rule_notes": "Companion to ISO 14040.",
        "why_recommended_template": "Recommended as the detailed requirements companion to ISO 14040 for conducting formal life cycle assessment studies.",
        "active": True,
    },
    {
        "slug": "iso-14046",
        "name": "ISO 14046",
        "short_name": "ISO 14046",
        "full_name": "ISO 14046 — Water Footprint Assessment",
        "stage": "measure",
        "topic": "water",
        "subtopic": "water_footprint",
        "description": "Principles, requirements and guidelines for water footprint assessment.",
        "what_it_is": "A standard for assessing water footprint based on LCA, covering water availability, water degradation, and water scarcity impacts.",
        "who_needs_it": [
            "Water-intensive industries needing quantified water impact data",
            "Organisations reporting to CDP Water or facing water-risk disclosure"
        ],
        "geography_applicability": ["global"],
        "region_applicability": ["global"],
        "industry_fit": ["manufacturing", "agriculture", "chemicals", "consumer-goods", "mining"],
        "org_size_fit": ["mid", "enterprise"],
        "mandatory_status": "voluntary",
        "certifiable": False,
        "output_type": "methodology",
        "prerequisites": ["Water consumption and discharge data", "LCA capability"],
        "data_requirements": ["Water intake volumes by source", "Water discharge volumes and quality", "Product-level water use data"],
        "maturity_min": "intermediate",
        "maturity_max": "advanced",
        "implementation_effort": "high",
        "assurance_relevance": "medium",
        "depends_on": [],
        "recommended_next": ["cdp-water", "aws-standard"],
        "priority_weight": 0.7,
        "recommendation_rule_notes": "Boost when water_intensity is high.",
        "why_recommended_template": "Recommended because your high water intensity requires quantified water footprint assessment for disclosure and risk management.",
        "active": True,
    },
    {
        "slug": "pcaf",
        "name": "PCAF",
        "short_name": "PCAF",
        "full_name": "Partnership for Carbon Accounting Financials",
        "stage": "measure",
        "topic": "finance",
        "subtopic": "financed_emissions",
        "description": "Standard for measuring and disclosing GHG emissions associated with loans and investments.",
        "what_it_is": "A methodology for financial institutions to assess and disclose Scope 3 financed emissions from lending and investment portfolios.",
        "who_needs_it": [
            "Banks, insurers and asset managers with lending or investment portfolios",
            "Financial institutions preparing for TCFD or ISSB disclosure"
        ],
        "geography_applicability": ["global"],
        "region_applicability": ["global"],
        "industry_fit": ["finance"],
        "org_size_fit": ["mid", "enterprise"],
        "mandatory_status": "voluntary",
        "certifiable": False,
        "output_type": "methodology",
        "prerequisites": ["Lending or investment portfolio data", "Counterparty emissions data or proxies"],
        "data_requirements": ["Portfolio exposure data", "Counterparty financial and emissions data", "Attribution factors"],
        "maturity_min": "basic",
        "maturity_max": "advanced",
        "implementation_effort": "high",
        "assurance_relevance": "high",
        "depends_on": ["ghg-protocol-corporate"],
        "recommended_next": ["tcfd", "ifrs-s2", "cdp-climate"],
        "priority_weight": 1.0,
        "recommendation_rule_notes": "Strongly boost for finance industry.",
        "why_recommended_template": "Recommended because as a financial institution, your financed emissions (Scope 3 Category 15) are likely your largest carbon impact and PCAF is the accepted methodology.",
        "active": True,
    },
    {
        "slug": "water-footprint",
        "name": "Water Footprint Methodology",
        "short_name": "Water Footprint",
        "full_name": "Water Footprint Network Methodology",
        "stage": "measure",
        "topic": "water",
        "subtopic": "water_accounting",
        "description": "Methodology for assessing blue, green and grey water footprints.",
        "what_it_is": "A comprehensive water accounting approach distinguishing blue water (surface/ground), green water (rainwater in soil), and grey water (dilution water for pollutants).",
        "who_needs_it": [
            "Agriculture and food & beverage companies",
            "Water-intensive manufacturers in stressed catchments"
        ],
        "geography_applicability": ["global"],
        "region_applicability": ["global"],
        "industry_fit": ["agriculture", "consumer-goods", "manufacturing", "chemicals"],
        "org_size_fit": ["sme", "mid", "enterprise"],
        "mandatory_status": "voluntary",
        "certifiable": False,
        "output_type": "methodology",
        "prerequisites": ["Water consumption tracking by source"],
        "data_requirements": ["Water intake, consumption, discharge data", "Catchment stress data"],
        "maturity_min": "basic",
        "maturity_max": "advanced",
        "implementation_effort": "medium",
        "assurance_relevance": "low",
        "depends_on": [],
        "recommended_next": ["iso-14046", "cdp-water"],
        "priority_weight": 0.6,
        "recommendation_rule_notes": "Boost when water_intensity is high.",
        "why_recommended_template": "Recommended because your water intensity calls for a structured water accounting methodology to quantify and manage water impacts.",
        "active": True,
    },

    # ======================================================================
    # REPORT (14 frameworks)
    # ======================================================================
    {
        "slug": "gri",
        "name": "GRI Standards",
        "short_name": "GRI",
        "full_name": "Global Reporting Initiative Standards",
        "stage": "report",
        "topic": "reporting",
        "subtopic": "multi_stakeholder",
        "description": "Multi-stakeholder sustainability reporting standard used worldwide.",
        "what_it_is": "A modular reporting standard (universal, sector and topic standards) built on impact materiality — reporting the organisation's effects on economy, environment and people.",
        "who_needs_it": [
            "Organisations publishing a voluntary sustainability report",
            "Companies with broad stakeholder audiences beyond investors"
        ],
        "geography_applicability": ["global"],
        "region_applicability": ["global"],
        "industry_fit": ["manufacturing", "energy", "chemicals", "construction", "transport", "technology", "consumer-goods", "agriculture", "finance", "healthcare", "mining", "retail"],
        "org_size_fit": ["sme", "mid", "enterprise"],
        "mandatory_status": "voluntary",
        "certifiable": False,
        "output_type": "disclosure",
        "prerequisites": ["Materiality assessment", "Reliable topic-level data for a full year"],
        "data_requirements": ["Environmental data (emissions, water, waste)", "Social data (workforce, community)", "Governance data"],
        "maturity_min": "basic",
        "maturity_max": "advanced",
        "implementation_effort": "medium",
        "assurance_relevance": "medium",
        "depends_on": ["ghg-protocol-corporate"],
        "recommended_next": ["csrd", "brsr", "ifrs-s1"],
        "priority_weight": 1.1,
        "recommendation_rule_notes": "Foundational reporting framework. Boost for reporting_improvement goals.",
        "why_recommended_template": "Recommended because GRI gives your sustainability report a recognised, impact-materiality structure that serves multi-stakeholder audiences.",
        "active": True,
    },
    {
        "slug": "brsr",
        "name": "BRSR",
        "short_name": "BRSR",
        "full_name": "Business Responsibility & Sustainability Report (India)",
        "stage": "report",
        "topic": "reporting",
        "subtopic": "regulatory_disclosure",
        "description": "SEBI-mandated ESG disclosure format for large listed Indian companies.",
        "what_it_is": "A prescribed disclosure format structured around the nine NGRBC principles, with essential and leadership indicators.",
        "who_needs_it": [
            "Top-1000 listed companies on Indian stock exchanges",
            "Value-chain partners of listed Indian companies"
        ],
        "geography_applicability": ["india"],
        "region_applicability": ["india"],
        "industry_fit": ["manufacturing", "energy", "chemicals", "construction", "transport", "technology", "consumer-goods", "agriculture", "finance", "healthcare", "mining", "retail"],
        "org_size_fit": ["mid", "enterprise"],
        "mandatory_status": "mandatory",
        "certifiable": False,
        "output_type": "disclosure",
        "prerequisites": ["Energy, water, waste and emissions data", "Workforce and social metrics"],
        "data_requirements": ["NGRBC principle-wise data", "Environmental performance indicators", "Social and governance metrics"],
        "maturity_min": "basic",
        "maturity_max": "advanced",
        "implementation_effort": "medium",
        "assurance_relevance": "high",
        "depends_on": ["ghg-protocol-corporate"],
        "recommended_next": ["brsr-core", "gri", "ifrs-s1"],
        "priority_weight": 1.4,
        "recommendation_rule_notes": "Mandatory for top-listed Indian companies. Strongly boost when region=india AND is_listed=true.",
        "why_recommended_template": "Recommended because you are a listed company in India and BRSR is the SEBI-prescribed disclosure format — alignment is mandatory.",
        "active": True,
    },
    {
        "slug": "brsr-core",
        "name": "BRSR Core",
        "short_name": "BRSR Core",
        "full_name": "BRSR Core — Assured ESG Attributes (India)",
        "stage": "report",
        "topic": "reporting",
        "subtopic": "regulatory_assurance",
        "description": "Subset of BRSR indicators subject to mandatory reasonable assurance.",
        "what_it_is": "A defined set of key ESG attributes from the BRSR that must undergo reasonable assurance by an independent assurance provider.",
        "who_needs_it": [
            "Top-listed Indian companies under SEBI assurance requirements",
            "Value-chain partners disclosing BRSR Core attributes"
        ],
        "geography_applicability": ["india"],
        "region_applicability": ["india"],
        "industry_fit": ["manufacturing", "energy", "chemicals", "construction", "transport", "technology", "consumer-goods", "agriculture", "finance", "healthcare", "mining", "retail"],
        "org_size_fit": ["mid", "enterprise"],
        "mandatory_status": "mandatory",
        "certifiable": False,
        "output_type": "disclosure",
        "prerequisites": ["BRSR report", "Audit-ready data systems", "Independent assurance provider"],
        "data_requirements": ["BRSR Core ESG attributes data", "Assurance-ready documentation"],
        "maturity_min": "intermediate",
        "maturity_max": "advanced",
        "implementation_effort": "high",
        "assurance_relevance": "high",
        "depends_on": ["brsr"],
        "recommended_next": ["gri", "ifrs-s1"],
        "priority_weight": 1.3,
        "recommendation_rule_notes": "Boost when region=india, is_listed=true, assurance_readiness is medium/high.",
        "why_recommended_template": "Recommended because BRSR Core attributes require reasonable assurance and your assurance readiness supports this next step.",
        "active": True,
    },
    {
        "slug": "ifrs-s1",
        "name": "IFRS S1",
        "short_name": "IFRS S1",
        "full_name": "IFRS S1 — General Sustainability Disclosure",
        "stage": "report",
        "topic": "reporting",
        "subtopic": "investor_disclosure",
        "description": "Investor-focused global baseline for general sustainability-related financial disclosures.",
        "what_it_is": "IFRS S1 covers general sustainability-related financial disclosures across governance, strategy, risk management, and metrics and targets.",
        "who_needs_it": [
            "Listed companies and those in jurisdictions adopting ISSB",
            "Organisations answering investor sustainability questions"
        ],
        "geography_applicability": ["global"],
        "region_applicability": ["global"],
        "industry_fit": ["manufacturing", "energy", "chemicals", "construction", "transport", "technology", "consumer-goods", "agriculture", "finance", "healthcare", "mining", "retail"],
        "org_size_fit": ["mid", "enterprise"],
        "mandatory_status": "quasi_mandatory",
        "certifiable": False,
        "output_type": "disclosure",
        "prerequisites": ["Sustainability risk and opportunity assessment", "Governance framework for sustainability"],
        "data_requirements": ["Cross-topic sustainability metrics", "Risk assessment documentation"],
        "maturity_min": "basic",
        "maturity_max": "advanced",
        "implementation_effort": "high",
        "assurance_relevance": "high",
        "depends_on": ["ghg-protocol-corporate"],
        "recommended_next": ["ifrs-s2", "tcfd"],
        "priority_weight": 1.2,
        "recommendation_rule_notes": "Boost when investor_pressure is high or is_listed is true.",
        "why_recommended_template": "Recommended because IFRS S1 is becoming the global investor-facing sustainability disclosure baseline and your investor exposure makes it relevant.",
        "active": True,
    },
    {
        "slug": "ifrs-s2",
        "name": "IFRS S2",
        "short_name": "IFRS S2",
        "full_name": "IFRS S2 — Climate-Related Disclosures",
        "stage": "report",
        "topic": "climate",
        "subtopic": "climate_disclosure",
        "description": "Investor-focused climate disclosure standard absorbing TCFD structure.",
        "what_it_is": "IFRS S2 covers climate-related financial disclosures including physical and transition risks, scenario analysis, and climate metrics and targets, absorbing the TCFD framework.",
        "who_needs_it": [
            "Listed companies and those in jurisdictions adopting ISSB",
            "Organisations answering investor climate-risk questions"
        ],
        "geography_applicability": ["global"],
        "region_applicability": ["global"],
        "industry_fit": ["manufacturing", "energy", "chemicals", "construction", "transport", "technology", "consumer-goods", "agriculture", "finance", "healthcare", "mining", "retail"],
        "org_size_fit": ["mid", "enterprise"],
        "mandatory_status": "quasi_mandatory",
        "certifiable": False,
        "output_type": "disclosure",
        "prerequisites": ["Scope 1 and 2 inventory", "Climate risk and scenario analysis"],
        "data_requirements": ["GHG emissions data (S1, S2, material S3)", "Climate scenario analysis", "Transition plan data"],
        "maturity_min": "basic",
        "maturity_max": "advanced",
        "implementation_effort": "high",
        "assurance_relevance": "high",
        "depends_on": ["ghg-protocol-corporate", "ifrs-s1"],
        "recommended_next": ["sbti", "tcfd"],
        "priority_weight": 1.2,
        "recommendation_rule_notes": "Boost when investor_pressure is high or finance industry.",
        "why_recommended_template": "Recommended because IFRS S2 climate disclosure is increasingly expected by investors and aligns with the TCFD structure your stakeholders already reference.",
        "active": True,
    },
    {
        "slug": "csrd",
        "name": "CSRD",
        "short_name": "CSRD",
        "full_name": "Corporate Sustainability Reporting Directive",
        "stage": "report",
        "topic": "reporting",
        "subtopic": "regulatory_disclosure",
        "description": "Mandatory EU reporting directive requiring sustainability disclosure under ESRS.",
        "what_it_is": "EU legislation requiring in-scope companies to report sustainability data with double materiality assessment, digital tagging and third-party assurance.",
        "who_needs_it": [
            "Large EU companies and EU-listed entities",
            "Non-EU groups with significant EU turnover and subsidiaries"
        ],
        "geography_applicability": ["eu"],
        "region_applicability": ["eu", "global"],
        "industry_fit": ["manufacturing", "energy", "chemicals", "construction", "transport", "technology", "consumer-goods", "agriculture", "finance", "healthcare", "mining", "retail"],
        "org_size_fit": ["mid", "enterprise"],
        "mandatory_status": "mandatory",
        "certifiable": False,
        "output_type": "disclosure",
        "prerequisites": ["Double materiality assessment", "Value-chain data collection process", "Audit-ready internal controls over sustainability data"],
        "data_requirements": ["ESRS datapoint coverage", "Double materiality documentation", "Value chain data"],
        "maturity_min": "intermediate",
        "maturity_max": "advanced",
        "implementation_effort": "high",
        "assurance_relevance": "high",
        "depends_on": ["ghg-protocol-corporate"],
        "recommended_next": ["esrs", "gri"],
        "priority_weight": 1.4,
        "recommendation_rule_notes": "Mandatory for EU-scope companies. Strongly boost when region=eu or export_exposure includes eu.",
        "why_recommended_template": "Recommended because your EU presence or market exposure puts CSRD in scope — it is mandatory, assured, and requires double materiality.",
        "active": True,
    },
    {
        "slug": "esrs",
        "name": "ESRS",
        "short_name": "ESRS",
        "full_name": "European Sustainability Reporting Standards",
        "stage": "report",
        "topic": "reporting",
        "subtopic": "regulatory_standards",
        "description": "The reporting standards under CSRD covering environment, social and governance topics.",
        "what_it_is": "The detailed disclosure standards under CSRD, structured into cross-cutting, environmental, social and governance modules with specific datapoints.",
        "who_needs_it": [
            "Companies in scope of CSRD",
            "Organisations preparing for EU sustainability reporting"
        ],
        "geography_applicability": ["eu"],
        "region_applicability": ["eu", "global"],
        "industry_fit": ["manufacturing", "energy", "chemicals", "construction", "transport", "technology", "consumer-goods", "agriculture", "finance", "healthcare", "mining", "retail"],
        "org_size_fit": ["mid", "enterprise"],
        "mandatory_status": "mandatory",
        "certifiable": False,
        "output_type": "disclosure",
        "prerequisites": ["CSRD applicability confirmed", "Double materiality assessment"],
        "data_requirements": ["Topic-specific ESRS datapoints", "Policies, actions, targets per material topic"],
        "maturity_min": "intermediate",
        "maturity_max": "advanced",
        "implementation_effort": "high",
        "assurance_relevance": "high",
        "depends_on": ["csrd"],
        "recommended_next": ["gri"],
        "priority_weight": 1.3,
        "recommendation_rule_notes": "Companion to CSRD. Always recommend together.",
        "why_recommended_template": "Recommended as the detailed reporting standard under CSRD — ESRS defines the specific datapoints and disclosures you must report.",
        "active": True,
    },
    {
        "slug": "tcfd",
        "name": "TCFD",
        "short_name": "TCFD",
        "full_name": "Task Force on Climate-related Financial Disclosures",
        "stage": "report",
        "topic": "climate",
        "subtopic": "climate_risk_disclosure",
        "description": "Climate risk disclosure structure now carried forward inside IFRS S2.",
        "what_it_is": "A four-pillar framework — governance, strategy, risk management, metrics and targets — for disclosing climate-related financial risks and opportunities.",
        "who_needs_it": [
            "Companies answering lender or investor climate risk questionnaires",
            "Organisations transitioning toward ISSB reporting"
        ],
        "geography_applicability": ["global"],
        "region_applicability": ["global"],
        "industry_fit": ["manufacturing", "energy", "chemicals", "construction", "transport", "technology", "consumer-goods", "agriculture", "finance", "healthcare", "mining", "retail"],
        "org_size_fit": ["sme", "mid", "enterprise"],
        "mandatory_status": "voluntary",
        "certifiable": False,
        "output_type": "disclosure",
        "prerequisites": ["Board oversight of climate", "Climate scenario analysis"],
        "data_requirements": ["GHG emissions data", "Climate risk assessment", "Scenario analysis results"],
        "maturity_min": "basic",
        "maturity_max": "advanced",
        "implementation_effort": "medium",
        "assurance_relevance": "medium",
        "depends_on": ["ghg-protocol-corporate"],
        "recommended_next": ["ifrs-s2", "cdp-climate"],
        "priority_weight": 1.0,
        "recommendation_rule_notes": "Boost when investor_pressure is high. Gateway to IFRS S2.",
        "why_recommended_template": "Recommended because TCFD's four-pillar climate risk structure is widely expected by lenders and investors and maps directly into IFRS S2.",
        "active": True,
    },
    {
        "slug": "sasb",
        "name": "SASB",
        "short_name": "SASB",
        "full_name": "SASB Standards (now part of ISSB)",
        "stage": "report",
        "topic": "reporting",
        "subtopic": "industry_specific_disclosure",
        "description": "Industry-specific financially material sustainability disclosure standards.",
        "what_it_is": "Standards defining financially material sustainability topics and metrics by industry, now maintained under the ISSB and referenced by IFRS S1.",
        "who_needs_it": [
            "Companies seeking industry-specific investor-grade metrics",
            "Organisations using ISSB standards"
        ],
        "geography_applicability": ["global"],
        "region_applicability": ["global"],
        "industry_fit": ["manufacturing", "energy", "chemicals", "construction", "transport", "technology", "consumer-goods", "agriculture", "finance", "healthcare", "mining", "retail"],
        "org_size_fit": ["mid", "enterprise"],
        "mandatory_status": "voluntary",
        "certifiable": False,
        "output_type": "disclosure",
        "prerequisites": ["Industry classification", "Financial materiality assessment"],
        "data_requirements": ["Industry-specific sustainability metrics"],
        "maturity_min": "basic",
        "maturity_max": "advanced",
        "implementation_effort": "medium",
        "assurance_relevance": "medium",
        "depends_on": [],
        "recommended_next": ["ifrs-s1", "ifrs-s2"],
        "priority_weight": 0.9,
        "recommendation_rule_notes": "Boost when investor_pressure is high.",
        "why_recommended_template": "Recommended because SASB provides industry-specific financially material metrics that investors use to compare your performance with peers.",
        "active": True,
    },
    {
        "slug": "cdp-climate",
        "name": "CDP Climate",
        "short_name": "CDP Climate",
        "full_name": "CDP Climate Change Questionnaire",
        "stage": "report",
        "topic": "climate",
        "subtopic": "scored_disclosure",
        "description": "Annual scored climate disclosure questionnaire requested by investors and customers.",
        "what_it_is": "An annual scored questionnaire covering governance, risks, opportunities, strategy, targets, and emissions data, widely used by procurement and investment teams.",
        "who_needs_it": [
            "Suppliers to large corporates that cascade CDP requests",
            "Companies wanting an external benchmark score"
        ],
        "geography_applicability": ["global"],
        "region_applicability": ["global"],
        "industry_fit": ["manufacturing", "energy", "chemicals", "construction", "transport", "technology", "consumer-goods", "agriculture", "finance", "healthcare", "mining", "retail"],
        "org_size_fit": ["sme", "mid", "enterprise"],
        "mandatory_status": "voluntary",
        "certifiable": False,
        "output_type": "rating",
        "prerequisites": ["Scope 1, 2 and material Scope 3 data", "Targets and governance detail"],
        "data_requirements": ["GHG inventory", "Climate targets", "Governance and strategy information"],
        "maturity_min": "basic",
        "maturity_max": "advanced",
        "implementation_effort": "medium",
        "assurance_relevance": "medium",
        "depends_on": ["ghg-protocol-corporate"],
        "recommended_next": ["tcfd", "sbti"],
        "priority_weight": 1.0,
        "recommendation_rule_notes": "Boost when customer_pressure is high or disclosure is required by supply chain.",
        "why_recommended_template": "Recommended because large buyers and investors commonly cascade CDP questionnaires — a scored response is often a procurement prerequisite.",
        "active": True,
    },
    {
        "slug": "cdp-water",
        "name": "CDP Water",
        "short_name": "CDP Water",
        "full_name": "CDP Water Security Questionnaire",
        "stage": "report",
        "topic": "water",
        "subtopic": "scored_disclosure",
        "description": "Annual scored water security disclosure questionnaire.",
        "what_it_is": "An annual scored questionnaire covering water accounting, risks, governance, strategy, and targets, used by investors to assess water-related risks.",
        "who_needs_it": [
            "Water-intensive companies responding to investor or customer water disclosure requests",
            "Companies in water-stressed regions"
        ],
        "geography_applicability": ["global"],
        "region_applicability": ["global"],
        "industry_fit": ["manufacturing", "agriculture", "chemicals", "consumer-goods", "mining"],
        "org_size_fit": ["mid", "enterprise"],
        "mandatory_status": "voluntary",
        "certifiable": False,
        "output_type": "rating",
        "prerequisites": ["Water consumption tracking", "Water risk assessment"],
        "data_requirements": ["Water intake, consumption, discharge data", "Water risk assessment", "Water targets"],
        "maturity_min": "basic",
        "maturity_max": "advanced",
        "implementation_effort": "medium",
        "assurance_relevance": "medium",
        "depends_on": [],
        "recommended_next": ["aws-standard", "iso-14046"],
        "priority_weight": 0.8,
        "recommendation_rule_notes": "Boost when water_intensity is high or customer_pressure is high.",
        "why_recommended_template": "Recommended because your water intensity and stakeholder expectations call for structured water security disclosure.",
        "active": True,
    },
    {
        "slug": "integrated-reporting",
        "name": "Integrated Reporting",
        "short_name": "IR",
        "full_name": "Integrated Reporting Framework (IIRC, now IFRS Foundation)",
        "stage": "report",
        "topic": "reporting",
        "subtopic": "value_creation",
        "description": "Framework for reporting how an organisation creates value over time using six capitals.",
        "what_it_is": "A framework for concise reporting on how strategy, governance, performance and prospects create value using financial, manufactured, intellectual, human, social and natural capitals.",
        "who_needs_it": [
            "Listed companies wanting concise investor-facing reporting",
            "Organisations integrating sustainability into mainstream annual reports"
        ],
        "geography_applicability": ["global"],
        "region_applicability": ["global"],
        "industry_fit": ["finance", "technology", "energy", "manufacturing"],
        "org_size_fit": ["mid", "enterprise"],
        "mandatory_status": "voluntary",
        "certifiable": False,
        "output_type": "disclosure",
        "prerequisites": ["Strategic clarity on value creation model", "Board-level engagement"],
        "data_requirements": ["Six-capitals performance data", "Strategy and outlook information"],
        "maturity_min": "intermediate",
        "maturity_max": "advanced",
        "implementation_effort": "medium",
        "assurance_relevance": "low",
        "depends_on": [],
        "recommended_next": ["ifrs-s1"],
        "priority_weight": 0.6,
        "recommendation_rule_notes": "Niche — for integrated report preparers.",
        "why_recommended_template": "Recommended because integrated reporting connects sustainability to your value creation story for investors.",
        "active": True,
    },
    {
        "slug": "ungc-cop",
        "name": "UNGC COP",
        "short_name": "UNGC COP",
        "full_name": "United Nations Global Compact — Communication on Progress",
        "stage": "report",
        "topic": "governance",
        "subtopic": "principles_disclosure",
        "description": "Annual disclosure for UN Global Compact signatories on ten principles progress.",
        "what_it_is": "An annual online questionnaire for UNGC participants covering human rights, labour, environment, and anti-corruption, with public disclosure.",
        "who_needs_it": [
            "Current or aspiring UNGC signatories",
            "Organisations wanting to demonstrate alignment with the ten principles"
        ],
        "geography_applicability": ["global"],
        "region_applicability": ["global"],
        "industry_fit": ["manufacturing", "energy", "chemicals", "construction", "transport", "technology", "consumer-goods", "agriculture", "finance", "healthcare", "mining", "retail"],
        "org_size_fit": ["sme", "mid", "enterprise"],
        "mandatory_status": "voluntary",
        "certifiable": False,
        "output_type": "disclosure",
        "prerequisites": ["UNGC membership or intent to join"],
        "data_requirements": ["Progress data across ten principles areas"],
        "maturity_min": "basic",
        "maturity_max": "advanced",
        "implementation_effort": "low",
        "assurance_relevance": "low",
        "depends_on": [],
        "recommended_next": ["gri", "sdgs"],
        "priority_weight": 0.6,
        "recommendation_rule_notes": "Low priority unless UNGC membership is a goal.",
        "why_recommended_template": "Recommended because UNGC participation demonstrates your commitment to global principles and connects to SDG reporting.",
        "active": True,
    },
    {
        "slug": "ecovadis",
        "name": "EcoVadis",
        "short_name": "EcoVadis",
        "full_name": "EcoVadis Sustainability Rating",
        "stage": "report",
        "topic": "supply_chain",
        "subtopic": "supplier_rating",
        "description": "Evidence-based supplier sustainability rating covering environment, labor, ethics and procurement.",
        "what_it_is": "A third-party sustainability rating platform that assesses companies across four themes: environment, labor & human rights, ethics, and sustainable procurement, producing a scored rating.",
        "who_needs_it": [
            "Suppliers to large corporates that mandate EcoVadis assessments",
            "Companies wanting a third-party ESG benchmark"
        ],
        "geography_applicability": ["global"],
        "region_applicability": ["global"],
        "industry_fit": ["manufacturing", "chemicals", "construction", "consumer-goods", "technology", "retail"],
        "org_size_fit": ["sme", "mid", "enterprise"],
        "mandatory_status": "voluntary",
        "certifiable": False,
        "output_type": "rating",
        "prerequisites": ["Sustainability policies and data across four themes"],
        "data_requirements": ["Environmental management data", "Labor and human rights policies", "Ethics and procurement policies"],
        "maturity_min": "basic",
        "maturity_max": "advanced",
        "implementation_effort": "medium",
        "assurance_relevance": "medium",
        "depends_on": [],
        "recommended_next": ["gri", "cdp-climate"],
        "priority_weight": 0.9,
        "recommendation_rule_notes": "Boost when customer_pressure is high or supply_chain_complexity is high.",
        "why_recommended_template": "Recommended because your supply chain position and customer expectations make a third-party sustainability rating valuable for maintaining business relationships.",
        "active": True,
    },

    # ======================================================================
    # IMPROVE (9 frameworks)
    # ======================================================================
    {
        "slug": "sdgs",
        "name": "UN SDGs",
        "short_name": "SDGs",
        "full_name": "United Nations Sustainable Development Goals",
        "stage": "improve",
        "topic": "governance",
        "subtopic": "global_goals",
        "description": "A shared 17-goal language for framing sustainability strategy and impact.",
        "what_it_is": "Seventeen global goals with 169 targets. Companies map material activities to specific SDG targets and indicators rather than claiming whole goals.",
        "who_needs_it": [
            "Organisations communicating purpose to employees, customers and communities",
            "Companies working with development finance or public sector buyers"
        ],
        "geography_applicability": ["global"],
        "region_applicability": ["global"],
        "industry_fit": ["manufacturing", "energy", "chemicals", "construction", "transport", "technology", "consumer-goods", "agriculture", "finance", "healthcare", "mining", "retail"],
        "org_size_fit": ["startup", "sme", "mid", "enterprise"],
        "mandatory_status": "voluntary",
        "certifiable": False,
        "output_type": "commitment",
        "prerequisites": ["Materiality view of where the business genuinely contributes"],
        "data_requirements": ["SDG target mapping", "Impact measurement data"],
        "maturity_min": "basic",
        "maturity_max": "advanced",
        "implementation_effort": "low",
        "assurance_relevance": "low",
        "depends_on": [],
        "recommended_next": ["sbti", "gri"],
        "priority_weight": 0.8,
        "recommendation_rule_notes": "General purpose. Boost when sustainability_goals includes sdg or impact.",
        "why_recommended_template": "Recommended because SDG mapping connects your material sustainability activities to globally recognised goals.",
        "active": True,
    },
    {
        "slug": "sbti",
        "name": "SBTi",
        "short_name": "SBTi",
        "full_name": "Science Based Targets initiative",
        "stage": "improve",
        "topic": "climate",
        "subtopic": "target_validation",
        "description": "Validated emissions targets aligned to 1.5°C pathways.",
        "what_it_is": "A target-setting and validation process. Companies submit near-term (and optionally net-zero) targets, which are checked against sector pathways and published once approved.",
        "who_needs_it": [
            "Companies committing publicly to net zero",
            "Suppliers whose customers require validated targets"
        ],
        "geography_applicability": ["global"],
        "region_applicability": ["global"],
        "industry_fit": ["manufacturing", "energy", "chemicals", "construction", "transport", "technology", "consumer-goods", "agriculture", "finance", "healthcare", "mining", "retail"],
        "org_size_fit": ["sme", "mid", "enterprise"],
        "mandatory_status": "voluntary",
        "certifiable": False,
        "output_type": "target",
        "prerequisites": [
            "A complete base-year Scope 1, 2 and screened Scope 3 inventory",
            "Executive sign-off on a reduction trajectory"
        ],
        "data_requirements": ["Base-year GHG inventory (S1, S2, screened S3)", "Target trajectory calculations", "Sector pathway data"],
        "maturity_min": "intermediate",
        "maturity_max": "advanced",
        "implementation_effort": "high",
        "assurance_relevance": "high",
        "depends_on": ["ghg-protocol-corporate", "ghg-protocol-scope3"],
        "recommended_next": ["net-zero-standard", "race-to-zero"],
        "priority_weight": 1.3,
        "recommendation_rule_notes": "Strongly boost when goals include net_zero. Apply dependency check — suppress if no baseline inventory.",
        "why_recommended_template": "Recommended because your net-zero ambition needs SBTi validation to turn it into a defensible, externally checked target.",
        "active": True,
    },
    {
        "slug": "net-zero-standard",
        "name": "Net Zero Standard",
        "short_name": "Net Zero",
        "full_name": "SBTi Corporate Net-Zero Standard",
        "stage": "improve",
        "topic": "climate",
        "subtopic": "net_zero",
        "description": "Rules for what a credible corporate net-zero claim requires.",
        "what_it_is": "Defines long-term deep decarbonisation (typically ~90%) before any neutralisation of residual emissions, plus interim near-term targets.",
        "who_needs_it": [
            "Organisations that have already published a net-zero ambition",
            "Companies needing to defend claims against greenwashing scrutiny"
        ],
        "geography_applicability": ["global"],
        "region_applicability": ["global"],
        "industry_fit": ["manufacturing", "energy", "chemicals", "construction", "transport", "technology", "consumer-goods", "agriculture", "finance", "healthcare", "mining", "retail"],
        "org_size_fit": ["mid", "enterprise"],
        "mandatory_status": "voluntary",
        "certifiable": False,
        "output_type": "target",
        "prerequisites": ["Validated near-term science-based targets", "Scope 3 reduction plan"],
        "data_requirements": ["Long-term reduction trajectory", "Residual emissions plan", "Neutralisation strategy"],
        "maturity_min": "advanced",
        "maturity_max": "advanced",
        "implementation_effort": "high",
        "assurance_relevance": "high",
        "depends_on": ["sbti", "ghg-protocol-corporate", "ghg-protocol-scope3"],
        "recommended_next": ["race-to-zero"],
        "priority_weight": 1.1,
        "recommendation_rule_notes": "Boost when goals include net_zero. Suppress if SBTi near-term not yet in place.",
        "why_recommended_template": "Recommended because a net-zero claim needs ~90% deep decarbonisation before neutralisation — this standard defines what you must evidence.",
        "active": True,
    },
    {
        "slug": "re100",
        "name": "RE100",
        "short_name": "RE100",
        "full_name": "RE100 — 100% Renewable Electricity",
        "stage": "improve",
        "topic": "energy",
        "subtopic": "renewable_energy",
        "description": "Global corporate commitment to source 100% renewable electricity.",
        "what_it_is": "A voluntary commitment and disclosure initiative for companies pledging to source 100% of electricity from renewable sources by a target date.",
        "who_needs_it": [
            "Electricity-intensive operations with large Scope 2 footprints",
            "Companies with Scope 2 reduction targets"
        ],
        "geography_applicability": ["global"],
        "region_applicability": ["global"],
        "industry_fit": ["manufacturing", "technology", "consumer-goods", "retail", "finance"],
        "org_size_fit": ["mid", "enterprise"],
        "mandatory_status": "voluntary",
        "certifiable": False,
        "output_type": "commitment",
        "prerequisites": ["Site-level electricity consumption data", "Market-based Scope 2 accounting"],
        "data_requirements": ["Electricity consumption data by source", "Renewable energy procurement data"],
        "maturity_min": "basic",
        "maturity_max": "advanced",
        "implementation_effort": "medium",
        "assurance_relevance": "medium",
        "depends_on": ["ghg-protocol-corporate"],
        "recommended_next": ["ep100", "sbti"],
        "priority_weight": 0.9,
        "recommendation_rule_notes": "Boost when energy_use_level is high and goals include renewable_energy.",
        "why_recommended_template": "Recommended because your high electricity consumption means Scope 2 is a key reduction lever — RE100 commitment converts intention into auditable action.",
        "active": True,
    },
    {
        "slug": "ep100",
        "name": "EP100",
        "short_name": "EP100",
        "full_name": "EP100 — Energy Productivity",
        "stage": "improve",
        "topic": "energy",
        "subtopic": "energy_productivity",
        "description": "Global commitment to double energy productivity or reach net-zero buildings.",
        "what_it_is": "A commitment to double energy productivity (economic output per unit of energy) or adopt net-zero carbon buildings by a target date.",
        "who_needs_it": [
            "Energy-intensive companies seeking operational efficiency targets",
            "Property and facilities-intensive organisations"
        ],
        "geography_applicability": ["global"],
        "region_applicability": ["global"],
        "industry_fit": ["manufacturing", "technology", "construction", "retail", "consumer-goods"],
        "org_size_fit": ["mid", "enterprise"],
        "mandatory_status": "voluntary",
        "certifiable": False,
        "output_type": "commitment",
        "prerequisites": ["Energy consumption and economic output baseline data"],
        "data_requirements": ["Energy consumption data", "Revenue or output data for productivity calculation"],
        "maturity_min": "basic",
        "maturity_max": "advanced",
        "implementation_effort": "medium",
        "assurance_relevance": "low",
        "depends_on": ["iso-50001"],
        "recommended_next": ["re100"],
        "priority_weight": 0.7,
        "recommendation_rule_notes": "Boost when goals include energy_productivity.",
        "why_recommended_template": "Recommended because your energy profile supports an energy productivity improvement commitment alongside efficiency management.",
        "active": True,
    },
    {
        "slug": "ev100",
        "name": "EV100",
        "short_name": "EV100",
        "full_name": "EV100 — Electric Vehicle Transition",
        "stage": "improve",
        "topic": "climate",
        "subtopic": "fleet_electrification",
        "description": "Global commitment to transition to electric vehicles by 2030.",
        "what_it_is": "A corporate commitment to transition owned/leased fleets to electric vehicles and install charging infrastructure by 2030.",
        "who_needs_it": [
            "Companies with large vehicle fleets",
            "Logistics and transport operators"
        ],
        "geography_applicability": ["global"],
        "region_applicability": ["global"],
        "industry_fit": ["transport", "retail", "consumer-goods", "construction", "energy"],
        "org_size_fit": ["mid", "enterprise"],
        "mandatory_status": "voluntary",
        "certifiable": False,
        "output_type": "commitment",
        "prerequisites": ["Fleet inventory data", "Electrification feasibility assessment"],
        "data_requirements": ["Fleet size and composition", "Fuel consumption data", "Charging infrastructure plans"],
        "maturity_min": "basic",
        "maturity_max": "advanced",
        "implementation_effort": "high",
        "assurance_relevance": "low",
        "depends_on": [],
        "recommended_next": ["re100", "sbti"],
        "priority_weight": 0.6,
        "recommendation_rule_notes": "Boost when goals include electrification or fleet_transition.",
        "why_recommended_template": "Recommended because your fleet operations can benefit from an EV transition commitment to reduce Scope 1 emissions and operational costs.",
        "active": True,
    },
    {
        "slug": "race-to-zero",
        "name": "Race to Zero",
        "short_name": "Race to Zero",
        "full_name": "UNFCCC Race to Zero Campaign",
        "stage": "improve",
        "topic": "climate",
        "subtopic": "net_zero_campaign",
        "description": "Global campaign for non-state actors to commit to net-zero by 2050.",
        "what_it_is": "A UN-backed campaign that mobilises cities, regions, businesses and investors to halve global emissions by 2030 and reach net-zero by 2050.",
        "who_needs_it": [
            "Companies joining through partner initiatives (SBTi, RE100, etc.)",
            "Organisations wanting to signal net-zero commitment at the highest level"
        ],
        "geography_applicability": ["global"],
        "region_applicability": ["global"],
        "industry_fit": ["manufacturing", "energy", "chemicals", "construction", "transport", "technology", "consumer-goods", "agriculture", "finance", "healthcare", "mining", "retail"],
        "org_size_fit": ["mid", "enterprise"],
        "mandatory_status": "voluntary",
        "certifiable": False,
        "output_type": "commitment",
        "prerequisites": ["Commitment via a partner initiative (e.g. SBTi)", "Net-zero target"],
        "data_requirements": ["Partner initiative membership", "Progress reporting"],
        "maturity_min": "intermediate",
        "maturity_max": "advanced",
        "implementation_effort": "low",
        "assurance_relevance": "low",
        "depends_on": ["sbti"],
        "recommended_next": ["net-zero-standard"],
        "priority_weight": 0.5,
        "recommendation_rule_notes": "Low priority — umbrella campaign. Follows SBTi commitment.",
        "why_recommended_template": "Recommended as the umbrella campaign that signals your net-zero commitment at the highest international level through your SBTi participation.",
        "active": True,
    },
    {
        "slug": "circulytics",
        "name": "Circulytics",
        "short_name": "Circulytics",
        "full_name": "Ellen MacArthur Foundation Circulytics",
        "stage": "improve",
        "topic": "circularity",
        "subtopic": "circular_economy",
        "description": "Circular economy measurement and benchmarking tool.",
        "what_it_is": "A company-level assessment tool measuring circular economy performance across enablers (strategy, innovation, people) and outcomes (material flows, energy, water).",
        "who_needs_it": [
            "Companies exploring circular business models",
            "Manufacturers with significant material waste or resource loops"
        ],
        "geography_applicability": ["global"],
        "region_applicability": ["global"],
        "industry_fit": ["manufacturing", "consumer-goods", "construction", "retail", "chemicals"],
        "org_size_fit": ["sme", "mid", "enterprise"],
        "mandatory_status": "voluntary",
        "certifiable": False,
        "output_type": "rating",
        "prerequisites": ["Material flow data", "Circular economy strategy or intent"],
        "data_requirements": ["Material input/output data", "Waste and recycling data", "Product life extension data"],
        "maturity_min": "basic",
        "maturity_max": "advanced",
        "implementation_effort": "medium",
        "assurance_relevance": "low",
        "depends_on": [],
        "recommended_next": ["true-zero-waste"],
        "priority_weight": 0.6,
        "recommendation_rule_notes": "Boost when waste_intensity is high or goals include circularity.",
        "why_recommended_template": "Recommended because your waste intensity and material flows can benefit from circular economy measurement and benchmarking.",
        "active": True,
    },
    {
        "slug": "true-zero-waste",
        "name": "TRUE Zero Waste",
        "short_name": "TRUE",
        "full_name": "TRUE Zero Waste Certification",
        "stage": "improve",
        "topic": "waste",
        "subtopic": "zero_waste",
        "description": "Certification for facilities achieving 90%+ diversion from landfill.",
        "what_it_is": "A third-party certification programme for facilities that divert at least 90% of waste from landfill, incineration and the environment through redesign, reduction, reuse, recycling and composting.",
        "who_needs_it": [
            "Facilities with significant waste generation",
            "Companies with zero-waste or circularity commitments"
        ],
        "geography_applicability": ["global"],
        "region_applicability": ["global"],
        "industry_fit": ["manufacturing", "consumer-goods", "retail", "construction", "technology"],
        "org_size_fit": ["sme", "mid", "enterprise"],
        "mandatory_status": "voluntary",
        "certifiable": True,
        "output_type": "certification",
        "prerequisites": ["Waste audit and characterisation study", "Diversion tracking system"],
        "data_requirements": ["Waste generation data by type", "Diversion rates", "Landfill data"],
        "maturity_min": "basic",
        "maturity_max": "advanced",
        "implementation_effort": "high",
        "assurance_relevance": "high",
        "depends_on": [],
        "recommended_next": ["circulytics"],
        "priority_weight": 0.7,
        "recommendation_rule_notes": "Boost when waste_intensity is high.",
        "why_recommended_template": "Recommended because your waste generation profile supports a zero-waste certification pathway to demonstrate circularity commitment.",
        "active": True,
    },
]


def seed_frameworks(db: Session) -> int:
    """
    Idempotently seeds the framework catalog into the database.
    Returns the total number of frameworks in catalog.
    """
    count = 0
    for data in INITIAL_FRAMEWORKS:
        existing = db.query(Framework).filter_by(slug=data["slug"]).first()
        if not existing:
            framework = Framework(**data)
            db.add(framework)
            count += 1
        else:
            # Update fields in case metadata changed
            for k, v in data.items():
                setattr(existing, k, v)
    db.commit()
    return len(INITIAL_FRAMEWORKS)


if __name__ == "__main__":
    from app.db.database import SessionLocal, engine, Base
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    try:
        count = seed_frameworks(db)
        print(f"Successfully seeded/verified {count} frameworks in the catalog.")
    finally:
        db.close()
