/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssessRouteImport } from './routes/assess'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as FrameworksIndexRouteImport } from './routes/frameworks.index'
import { Route as FrameworksSlugRouteImport } from './routes/frameworks.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessRoute = AssessRouteImport.update({
  id: '/assess',
  path: '/assess',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const FrameworksIndexRoute = FrameworksIndexRouteImport.update({
  id: '/frameworks/',
  path: '/frameworks/',
  getParentRoute: () => rootRouteImport,
} as any)
const FrameworksSlugRoute = FrameworksSlugRouteImport.update({
  id: '/frameworks/$slug',
  path: '/frameworks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assess': typeof AssessRoute
  '/results': typeof ResultsRoute
  '/frameworks/$slug': typeof FrameworksSlugRoute
  '/frameworks/': typeof FrameworksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assess': typeof AssessRoute
  '/results': typeof ResultsRoute
  '/frameworks/$slug': typeof FrameworksSlugRoute
  '/frameworks': typeof FrameworksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assess': typeof AssessRoute
  '/results': typeof ResultsRoute
  '/frameworks/$slug': typeof FrameworksSlugRoute
  '/frameworks/': typeof FrameworksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/assess' | '/results' | '/frameworks/$slug' | '/frameworks/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/assess' | '/results' | '/frameworks/$slug' | '/frameworks'
  id:
    | '__root__'
    | '/'
    | '/assess'
    | '/results'
    | '/frameworks/$slug'
    | '/frameworks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessRoute: typeof AssessRoute
  ResultsRoute: typeof ResultsRoute
  FrameworksSlugRoute: typeof FrameworksSlugRoute
  FrameworksIndexRoute: typeof FrameworksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assess': {
      id: '/assess'
      path: '/assess'
      fullPath: '/assess'
      preLoaderRoute: typeof AssessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frameworks/': {
      id: '/frameworks/'
      path: '/frameworks'
      fullPath: '/frameworks/'
      preLoaderRoute: typeof FrameworksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frameworks/$slug': {
      id: '/frameworks/$slug'
      path: '/frameworks/$slug'
      fullPath: '/frameworks/$slug'
      preLoaderRoute: typeof FrameworksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessRoute: AssessRoute,
  ResultsRoute: ResultsRoute,
  FrameworksSlugRoute: FrameworksSlugRoute,
  FrameworksIndexRoute: FrameworksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
